name: Build
on: [ pull_request, push, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@main
      - name: Setup JDK 21
        uses: actions/setup-java@main
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Setup website files
        run: ./gradlew fabric:setupWebsiteFiles
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup Node packages
        run: npm ci --prefix buildSrc/src/main/resources/website
      - name: Build Angular
        run: npm run build --prefix buildSrc/src/main/resources/website
      - name: Setup files
        run: ./gradlew common:setupFiles -Pcrowdin_api_key="${{ secrets.CROWDIN_API_KEY }}" -Ppatreon_api_key="${{ secrets.PATREON_API_KEY }}"
      - name: Build mod
        run: ./gradlew build
      - name: Capture release artifacts
        uses: actions/upload-artifact@main
        with:
          name: Fabric and NeoForge
          path: build/release/
      - name: Post Crowdin translation analysis
        run: cat build/translation/analysis.md >> $GITHUB_STEP_SUMMARY
        continue-on-error: true
