name: Build
on: [ pull_request, push ]

jobs:
  build:
    strategy:
      matrix:
        minecraft: [ 1.16.5, 1.17.1, 1.18, 1.18.2, 1.19 ]
        loader: [ fabric, forge, common ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build ${{ matrix.minecraft }} ${{ matrix.loader }}
        run: ./gradlew ${{ matrix.loader }}:build -PbuildVersion="${{ matrix.minecraft }}" -PpatreonApiKey="${{ secrets.PATREON_API_KEY }}"
      - name: Capture release artifacts
        if: matrix.loader != 'common'
        uses: actions/upload-artifact@v2
        with:
          name: Fabric and Forge
          path: build/release/
      - name: Capture lib artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Libraries
          path: build/libs/
  crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Upload Translations to Crowdin
        env:
          MY_KEY: ${{ secrets.CROWDIN_API_KEY }}
        if: ${{ env.MY_KEY != '' && github.ref == 'refs/heads/master' }}
        uses: crowdin/github-action@1.4.8
        with:
          upload_sources: true
          upload_translations: false
          download_translations: false
          push_translations: false
          create_pull_request: false
          project_id: '455212'
          token: ${{ secrets.CROWDIN_API_KEY }}
          config: 'crowdin.yml'
